AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  iot2aps-lambda

  Sample SAM Template for iot2aps-lambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Parameters:
  WorkspaceIdParameter:
    Type: String
  MetricsNameParameter:
    Type: String
  TopicParameter:
    Type: String

Resources:
  IoT2ApsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: iot2aps/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Environment:
        Variables:
          WORKSPACE_ID: !Ref WorkspaceIdParameter
          METRICS_NAME: !Ref MetricsNameParameter
      Events:
        IoTRule:
          Type: IoTRule
          Properties: 
            Sql: !Sub "SELECT topic() as topic, clientid() as thing_name, timestamp() as timestamp, * as payload FROM '${TopicParameter}'"
      Policies:
        - AmazonPrometheusRemoteWriteAccess


# Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
